#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow
requirements:
  - class: ScatterFeatureRequirement
inputs:
  intervals: File[]?
  # Read samples, bam format
  # NOTE: Should be at least 20 samples for exome
  mapped_reads: File[]
  # reference genome, fasta
  reference_genome: File
  # Number of threads to use
  threads: int?
  # GATK
  GATKJar: File
  # Variant calling
  # Confidence threshold for calling a variant - 30
  stand_call_conf: double
  # Variant Recalibration - SNPs
  snp_resource_hapmap: File
  snp_resource_omni: File
  snp_resource_1kg: File
  # Variant Recalibration - Common
  resource_dbsnp: File
  # Variant Recalibration - Indels
  indel_resource_mills: File

outputs:
  per_sample_raw_variants:
    type: File[]
    outputSource: variant_calling/output_HaplotypeCaller
    doc: "VCF files from per sample variant calling"
  joint_raw_variants:
    type: File
    outputSource: joint_genotyping/output_GenotypeGVCFs
    doc: "VCF file from joint genotyping calling"
  variant_recalibration_snps_tranches:
    type: File
    outputSource: variant_recalibration_snps/tranches_File
    doc: "The output tranches file used by ApplyRecalibration in SNP mode"
  variant_recalibration_snps_recal:
    type: File
    outputSource: variant_recalibration_snps/recal_File
    doc: "The output recal file used by ApplyRecalibration in SNP mode"
  variant_recalibration_snps_rscript:
    type: File
    outputSource: variant_recalibration_snps/vqsr_rscript
    doc: "The output rscript file generated by the VQSR in SNP mode to aid in visualization of the input data and learned model"
  variant_recalibration_indels_tranches:
    type: File
    outputSource: variant_recalibration_indels/tranches_File
    doc: "The output tranches file used by ApplyRecalibration in INDEL mode"
  variant_recalibration_indels_recal:
    type: File
    outputSource: variant_recalibration_indels/recal_File
    doc: "The output recal file used by ApplyRecalibration in INDEL mode"
  variant_recalibration_indels_rscript:
    type: File
    outputSource: variant_recalibration_indels/vqsr_rscript
    doc: "The output rscript file generated by the VQSR in INDEL mode to aid in visualization of the input data and learned model"
  variant_recalibration_snps_vcf:
    type: File
    outputSource: apply_recalibration_snps/output_recalibrated_vcf
    doc: "The output filtered and recalibrated VCF file in SNP mode in which each variant is annotated with its VQSLOD value"
  variant_recalibration_indels_vcf:
    type: File
    outputSource: apply_recalibration_indels/output_recalibrated_vcf
    doc: "The output filtered and recalibrated VCF file in INDEL mode in which each variant is annotated with its VQSLOD value"
steps:
  variant_calling:
    # Does not support multiple threads
    run: ../community-workflows/tools/GATK-HaplotypeCaller.cwl
    # Each step uses one core and about 2GB RAM
    requirements:
      - class: ResourceRequirement
        coresMin: 1
        ramMin: 2560
    scatter: inputBam_HaplotypeCaller
    in:
      GATKJar: GATKJar
      inputBam_HaplotypeCaller: mapped_reads
      intervals: intervals
      reference: reference_genome
      genotyping_mode:
        default: "DISCOVERY"
      stand_call_conf: stand_call_conf
      emitRefConfidence:
        default: "GVCF"
      outputfile_HaplotypeCaller: #
        # Naming your output file using the .g.vcf extension will automatically set the appropriate values  for --variant_index_type and --variant_index_parameter
        default: "raw_variants.g.vcf"
    out:
      - output_HaplotypeCaller
  # TODO: At this point, should merge VCFs if we had lots of them
  # See Merge (optional) on https://software.broadinstitute.org/gatk/best-practices/bp_3step.php?case=GermShortWGS&p=2
  joint_genotyping:
    run: ../community-workflows/tools/GATK-GenotypeGVCFs.cwl
    requirements:
      - class: ResourceRequirement
        coresMin: 1
        ramMin: 12288
    in:
      GATKJar: GATKJar
      # https://gatkforums.broadinstitute.org/wdl/discussion/8718/concurrentmodificationexception-in-gatk-3-7-genotypegvcfs
      # Hi all, it looks like some race conditions were introduced in 3.7. Unfortunately we can't devote effort to addressing that since we are moving away from using this type of parallelism altogether
      threads:
        default: 1
      intervals: intervals
      # NOTE: GATK best practices recommends at least 30 samples for exome - how to deal?
      variants: variant_calling/output_HaplotypeCaller
      reference: reference_genome
      outputfile_GenotypeGVCFs:
        default: "joint_genotype_raw_variants.g.vcf"
    out:
      - output_GenotypeGVCFs
  # Recommendations from https://software.broadinstitute.org/gatk/documentation/article?id=1259
  variant_recalibration_snps:
    run: ../community-workflows/tools/GATK-VariantRecalibrator-SNPs.cwl
    in:
      GATKJar: GATKJar
      intervals: intervals
      reference: reference_genome
      variants: joint_genotyping/output_GenotypeGVCFs
      threads:
        default: 1
      outputfile_recal:
        default: "snps_vqsr_recal.out"
      outputfile_tranches:
        default: "snps_vqsr_tranches.out"
      outputfile_rscript:
        default: "snps_vqsr.R"
      resource_hapmap: snp_resource_hapmap
      resource_omni: snp_resource_omni
      resource_1kg: snp_resource_1kg
      resource_dbsnp: resource_dbsnp
      # annotations, See https://software.broadinstitute.org/gatk/documentation/article?id=1259
      # Removed DP and InbreedingCoeff
      # Please note that these recommendations are formulated for whole-genome datasets.
      # For exomes, we do not recommend using DP for variant recalibration (see below for details of why).
      annotations:
        # The InbreedingCoeff is a population level statistic that requires at least 10 samples in order to be computed. For projects with fewer samples, or that includes many closely related samples (such as a family) please omit this annotation from the command line.
        # NOTE: InbreedingCoeff would need to be annotated separately
        default: ["QD","MQ","MQRankSum","ReadPosRankSum","FS","SOR"]
    out:
      - tranches_File
      - recal_File
      - vqsr_rscript
  apply_recalibration_snps:
    run: ../community-workflows/tools/GATK-ApplyRecalibration.cwl
    in:
      GATKJar: GATKJar
      intervals: intervals
      reference: reference_genome
      variants: joint_genotyping/output_GenotypeGVCFs
      threads: threads
      tranches_file: variant_recalibration_snps/tranches_File
      recal_file: variant_recalibration_snps/recal_File
      outputfile_recalibrated_vcf:
        default: "snps_recalibrated.vcf"
      ts_filter_level:
        default: 99.5
      mode:
        default: "SNP"
    out:
      - output_recalibrated_vcf
  variant_recalibration_indels:
    run: ../community-workflows/tools/GATK-VariantRecalibrator-Indels.cwl
    in:
      GATKJar: GATKJar
      intervals: intervals
      reference: reference_genome
      variants: joint_genotyping/output_GenotypeGVCFs
      threads:
        default: 1
      outputfile_recal:
        default: "indels_vqsr_recal.out"
      outputfile_tranches:
        default: "indels_vqsr_tranches.out"
      outputfile_rscript:
        default: "indels_vqsr.R"
      resource_mills: indel_resource_mills
      resource_dbsnp: resource_dbsnp
      # annotations, See https://software.broadinstitute.org/gatk/documentation/article?id=1259
      # Removed DP and InbreedingCoeff
      # Please note that these recommendations are formulated for whole-genome datasets.
      # For exomes, we do not recommend using DP for variant recalibration (see below for details of why).
      annotations:
        # The InbreedingCoeff is a population level statistic that requires at least 10 samples in order to be computed. For projects with fewer samples, or that includes many closely related samples (such as a family) please omit this annotation from the command line.
        # NOTE: InbreedingCoeff would need to be annotated separately
                default: ["QD","FS","SOR","ReadPosRankSum","MQRankSum"]
    out:
      - tranches_File
      - recal_File
      - vqsr_rscript
  apply_recalibration_indels:
    run: ../community-workflows/tools/GATK-ApplyRecalibration.cwl
    in:
      GATKJar: GATKJar
      intervals: intervals
      reference: reference_genome
      variants: joint_genotyping/output_GenotypeGVCFs
      threads: threads
      tranches_file: variant_recalibration_indels/tranches_File
      recal_file: variant_recalibration_indels/recal_File
      outputfile_recalibrated_vcf:
        default: "indels_recalibrated.vcf"
      ts_filter_level:
        default: 99.0
      mode:
        default: "INDEL"
    out:
      - output_recalibrated_vcf
