FROM python:2.7
MAINTAINER dan.leehr@duke.edu

ENV TZ=US/Eastern
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y build-essential
RUN pip install numpy
RUN pip install matplotlib
RUN pip install HTSeq
